"""
365 Bible Verses — one for every day of the year.
Organized by theme, deterministically mapped to each day via day-of-year index.
"""

DAILY_VERSES = [
    # --- JANUARY: Love & God's Character (1-31) ---
    {"verse": "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", "reference": "John 3:16", "theme": "Love"},
    {"verse": "The Lord is compassionate and gracious, slow to anger, abounding in love.", "reference": "Psalm 103:8", "theme": "Love"},
    {"verse": "We love because he first loved us.", "reference": "1 John 4:19", "theme": "Love"},
    {"verse": "See what great love the Father has lavished on us, that we should be called children of God!", "reference": "1 John 3:1", "theme": "Love"},
    {"verse": "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", "reference": "Romans 5:8", "theme": "Love"},
    {"verse": "Neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.", "reference": "Romans 8:39", "theme": "Love"},
    {"verse": "Dear friends, let us love one another, for love comes from God.", "reference": "1 John 4:7", "theme": "Love"},
    {"verse": "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you.", "reference": "Zephaniah 3:17", "theme": "Love"},
    {"verse": "I have loved you with an everlasting love; I have drawn you with unfailing kindness.", "reference": "Jeremiah 31:3", "theme": "Love"},
    {"verse": "How great is the love the Father has lavished on us, that we should be called children of God! And that is what we are!", "reference": "1 John 3:1", "theme": "Love"},
    {"verse": "Give thanks to the Lord, for he is good; his love endures forever.", "reference": "Psalm 107:1", "theme": "Gratitude"},
    {"verse": "God is love. Whoever lives in love lives in God, and God in them.", "reference": "1 John 4:16", "theme": "Love"},
    {"verse": "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", "reference": "1 Corinthians 13:4", "theme": "Love"},
    {"verse": "It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs.", "reference": "1 Corinthians 13:5", "theme": "Love"},
    {"verse": "Love never fails. But where there are prophecies, they will cease; where there are tongues, they will be stilled.", "reference": "1 Corinthians 13:8", "theme": "Love"},
    {"verse": "And now these three remain: faith, hope and love. But the greatest of these is love.", "reference": "1 Corinthians 13:13", "theme": "Love"},
    {"verse": "Above all, love each other deeply, because love covers over a multitude of sins.", "reference": "1 Peter 4:8", "theme": "Love"},
    {"verse": "A new command I give you: Love one another. As I have loved you, so you must love one another.", "reference": "John 13:34", "theme": "Love"},
    {"verse": "Greater love has no one than this: to lay down one's life for one's friends.", "reference": "John 15:13", "theme": "Love"},
    {"verse": "And over all these virtues put on love, which binds them all together in perfect unity.", "reference": "Colossians 3:14", "theme": "Love"},
    {"verse": "The Lord is good, a refuge in times of trouble. He cares for those who trust in him.", "reference": "Nahum 1:7", "theme": "Love"},
    {"verse": "The Lord is faithful to all his promises and loving toward all he has made.", "reference": "Psalm 145:13", "theme": "Faithfulness"},
    {"verse": "Because of the Lord's great love we are not consumed, for his compassions never fail.", "reference": "Lamentations 3:22", "theme": "Love"},
    {"verse": "They are new every morning; great is your faithfulness.", "reference": "Lamentations 3:23", "theme": "Faithfulness"},
    {"verse": "For the Lord is good and his love endures forever; his faithfulness continues through all generations.", "reference": "Psalm 100:5", "theme": "Faithfulness"},
    {"verse": "Your love, Lord, reaches to the heavens, your faithfulness to the skies.", "reference": "Psalm 36:5", "theme": "Faithfulness"},
    {"verse": "Know therefore that the Lord your God is God; he is the faithful God, keeping his covenant of love.", "reference": "Deuteronomy 7:9", "theme": "Faithfulness"},
    {"verse": "Let the morning bring me word of your unfailing love, for I have put my trust in you.", "reference": "Psalm 143:8", "theme": "Love"},
    {"verse": "The Lord appeared to us in the past, saying: I have loved you with an everlasting love.", "reference": "Jeremiah 31:3", "theme": "Love"},
    {"verse": "How priceless is your unfailing love, O God! People take refuge in the shadow of your wings.", "reference": "Psalm 36:7", "theme": "Love"},
    {"verse": "May the Lord direct your hearts into God's love and Christ's perseverance.", "reference": "2 Thessalonians 3:5", "theme": "Love"},

    # --- FEBRUARY: Faith & Trust (32-59) ---
    {"verse": "Now faith is confidence in what we hope for and assurance about what we do not see.", "reference": "Hebrews 11:1", "theme": "Faith"},
    {"verse": "Trust in the Lord with all your heart and lean not on your own understanding.", "reference": "Proverbs 3:5", "theme": "Trust"},
    {"verse": "In all your ways submit to him, and he will make your paths straight.", "reference": "Proverbs 3:6", "theme": "Trust"},
    {"verse": "For we walk by faith, not by sight.", "reference": "2 Corinthians 5:7", "theme": "Faith"},
    {"verse": "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists.", "reference": "Hebrews 11:6", "theme": "Faith"},
    {"verse": "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God.", "reference": "Galatians 2:20", "theme": "Faith"},
    {"verse": "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.", "reference": "Ephesians 2:8", "theme": "Faith"},
    {"verse": "So then faith comes by hearing, and hearing by the word of God.", "reference": "Romans 10:17", "theme": "Faith"},
    {"verse": "When I am afraid, I put my trust in you.", "reference": "Psalm 56:3", "theme": "Trust"},
    {"verse": "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.", "reference": "Psalm 18:2", "theme": "Trust"},
    {"verse": "Blessed is the one who trusts in the Lord, whose confidence is in him.", "reference": "Jeremiah 17:7", "theme": "Trust"},
    {"verse": "Those who know your name trust in you, for you, Lord, have never forsaken those who seek you.", "reference": "Psalm 9:10", "theme": "Trust"},
    {"verse": "Commit your way to the Lord; trust in him and he will do this.", "reference": "Psalm 37:5", "theme": "Trust"},
    {"verse": "Trust in him at all times, you people; pour out your hearts to him, for God is our refuge.", "reference": "Psalm 62:8", "theme": "Trust"},
    {"verse": "It is better to take refuge in the Lord than to trust in humans.", "reference": "Psalm 118:8", "theme": "Trust"},
    {"verse": "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", "reference": "Psalm 28:7", "theme": "Trust"},
    {"verse": "But I trust in your unfailing love; my heart rejoices in your salvation.", "reference": "Psalm 13:5", "theme": "Trust"},
    {"verse": "Some trust in chariots and some in horses, but we trust in the name of the Lord our God.", "reference": "Psalm 20:7", "theme": "Trust"},
    {"verse": "Jesus said to him, 'If you can believe, all things are possible to him who believes.'", "reference": "Mark 9:23", "theme": "Faith"},
    {"verse": "Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move.", "reference": "Matthew 17:20", "theme": "Faith"},
    {"verse": "Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die.'", "reference": "John 11:25", "theme": "Faith"},
    {"verse": "Let us fix our eyes on Jesus, the author and perfecter of our faith.", "reference": "Hebrews 12:2", "theme": "Faith"},
    {"verse": "The righteous will live by faith.", "reference": "Romans 1:17", "theme": "Faith"},
    {"verse": "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.", "reference": "James 1:2-3", "theme": "Faith"},
    {"verse": "Be on your guard; stand firm in the faith; be courageous; be strong.", "reference": "1 Corinthians 16:13", "theme": "Faith"},
    {"verse": "Fight the good fight of the faith. Take hold of the eternal life to which you were called.", "reference": "1 Timothy 6:12", "theme": "Faith"},
    {"verse": "I have fought the good fight, I have finished the race, I have kept the faith.", "reference": "2 Timothy 4:7", "theme": "Faith"},
    {"verse": "For in the gospel the righteousness of God is revealed — a righteousness that is by faith from first to last.", "reference": "Romans 1:17", "theme": "Faith"},

    # --- MARCH: Strength & Courage (60-90) ---
    {"verse": "I can do all this through him who gives me strength.", "reference": "Philippians 4:13", "theme": "Strength"},
    {"verse": "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", "reference": "Joshua 1:9", "theme": "Courage"},
    {"verse": "The Lord is my light and my salvation — whom shall I fear?", "reference": "Psalm 27:1", "theme": "Courage"},
    {"verse": "God is our refuge and strength, an ever-present help in trouble.", "reference": "Psalm 46:1", "theme": "Strength"},
    {"verse": "But those who hope in the Lord will renew their strength. They will soar on wings like eagles.", "reference": "Isaiah 40:31", "theme": "Strength"},
    {"verse": "So do not fear, for I am with you; do not be dismayed, for I am your God.", "reference": "Isaiah 41:10", "theme": "Courage"},
    {"verse": "I will strengthen you and help you; I will uphold you with my righteous right hand.", "reference": "Isaiah 41:10", "theme": "Strength"},
    {"verse": "The Lord is my strength and my song; he has become my salvation.", "reference": "Exodus 15:2", "theme": "Strength"},
    {"verse": "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged.", "reference": "Joshua 1:9", "theme": "Courage"},
    {"verse": "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", "reference": "2 Timothy 1:7", "theme": "Courage"},
    {"verse": "Be strong in the Lord and in his mighty power.", "reference": "Ephesians 6:10", "theme": "Strength"},
    {"verse": "The Lord is the stronghold of my life — of whom shall I be afraid?", "reference": "Psalm 27:1", "theme": "Courage"},
    {"verse": "Wait for the Lord; be strong and take heart and wait for the Lord.", "reference": "Psalm 27:14", "theme": "Strength"},
    {"verse": "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.", "reference": "Psalm 73:26", "theme": "Strength"},
    {"verse": "The Lord gives strength to his people; the Lord blesses his people with peace.", "reference": "Psalm 29:11", "theme": "Strength"},
    {"verse": "He gives strength to the weary and increases the power of the weak.", "reference": "Isaiah 40:29", "theme": "Strength"},
    {"verse": "Be on your guard; stand firm in the faith; be courageous; be strong.", "reference": "1 Corinthians 16:13", "theme": "Courage"},
    {"verse": "I sought the Lord, and he answered me; he delivered me from all my fears.", "reference": "Psalm 34:4", "theme": "Courage"},
    {"verse": "When I called, you answered me; you greatly emboldened me.", "reference": "Psalm 138:3", "theme": "Courage"},
    {"verse": "Do not be afraid of them; the Lord your God himself will fight for you.", "reference": "Deuteronomy 3:22", "theme": "Courage"},
    {"verse": "The Lord your God is the one who goes with you to fight for you against your enemies to give you victory.", "reference": "Deuteronomy 20:4", "theme": "Courage"},
    {"verse": "Be strong and courageous, for you must go with this people into the land.", "reference": "Deuteronomy 31:7", "theme": "Courage"},
    {"verse": "In God I trust and am not afraid. What can mere mortals do to me?", "reference": "Psalm 56:11", "theme": "Courage"},
    {"verse": "Even though I walk through the darkest valley, I will fear no evil, for you are with me.", "reference": "Psalm 23:4", "theme": "Courage"},
    {"verse": "The Lord is with me; I will not be afraid. What can mere mortals do to me?", "reference": "Psalm 118:6", "theme": "Courage"},
    {"verse": "Fear not, for I have redeemed you; I have summoned you by name; you are mine.", "reference": "Isaiah 43:1", "theme": "Courage"},
    {"verse": "When you pass through the waters, I will be with you.", "reference": "Isaiah 43:2", "theme": "Courage"},
    {"verse": "Do not be afraid; do not be discouraged. Go out to face them tomorrow, and the Lord will be with you.", "reference": "2 Chronicles 20:17", "theme": "Courage"},
    {"verse": "The Lord himself goes before you and will be with you; he will never leave you nor forsake you.", "reference": "Deuteronomy 31:8", "theme": "Courage"},
    {"verse": "No weapon forged against you will prevail.", "reference": "Isaiah 54:17", "theme": "Strength"},
    {"verse": "My grace is sufficient for you, for my power is made perfect in weakness.", "reference": "2 Corinthians 12:9", "theme": "Strength"},

    # --- APRIL: Hope & Promises (91-120) ---
    {"verse": "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", "reference": "Jeremiah 29:11", "theme": "Hope"},
    {"verse": "And we know that in all things God works for the good of those who love him.", "reference": "Romans 8:28", "theme": "Hope"},
    {"verse": "May the God of hope fill you with all joy and peace as you trust in him.", "reference": "Romans 15:13", "theme": "Hope"},
    {"verse": "Why, my soul, are you downcast? Put your hope in God, for I will yet praise him, my Savior and my God.", "reference": "Psalm 42:11", "theme": "Hope"},
    {"verse": "Be joyful in hope, patient in affliction, faithful in prayer.", "reference": "Romans 12:12", "theme": "Hope"},
    {"verse": "But as for me, I watch in hope for the Lord, I wait for God my Savior; my God will hear me.", "reference": "Micah 7:7", "theme": "Hope"},
    {"verse": "For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures and the encouragement they provide we might have hope.", "reference": "Romans 15:4", "theme": "Hope"},
    {"verse": "The Lord is my portion; therefore I will wait for him.", "reference": "Lamentations 3:24", "theme": "Hope"},
    {"verse": "I wait for the Lord, my whole being waits, and in his word I put my hope.", "reference": "Psalm 130:5", "theme": "Hope"},
    {"verse": "We have this hope as an anchor for the soul, firm and secure.", "reference": "Hebrews 6:19", "theme": "Hope"},
    {"verse": "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope.", "reference": "1 Peter 1:3", "theme": "Hope"},
    {"verse": "The Lord delights in those who fear him, who put their hope in his unfailing love.", "reference": "Psalm 147:11", "theme": "Hope"},
    {"verse": "Find rest, my soul, in God alone; my hope comes from him.", "reference": "Psalm 62:5", "theme": "Hope"},
    {"verse": "Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long.", "reference": "Psalm 25:5", "theme": "Hope"},
    {"verse": "No one who hopes in you will ever be put to shame.", "reference": "Psalm 25:3", "theme": "Hope"},
    {"verse": "The eyes of the Lord are on those who fear him, on those whose hope is in his unfailing love.", "reference": "Psalm 33:18", "theme": "Hope"},
    {"verse": "And hope does not put us to shame, because God's love has been poured out into our hearts through the Holy Spirit.", "reference": "Romans 5:5", "theme": "Hope"},
    {"verse": "But blessed is the one who trusts in the Lord, whose confidence is in him. They will be like a tree planted by the water.", "reference": "Jeremiah 17:7-8", "theme": "Hope"},
    {"verse": "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.", "reference": "Revelation 21:4", "theme": "Hope"},
    {"verse": "Behold, I am making all things new.", "reference": "Revelation 21:5", "theme": "Hope"},
    {"verse": "For with God nothing shall be impossible.", "reference": "Luke 1:37", "theme": "Hope"},
    {"verse": "Jesus looked at them and said, 'With man this is impossible, but with God all things are possible.'", "reference": "Matthew 19:26", "theme": "Hope"},
    {"verse": "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", "reference": "Psalm 34:18", "theme": "Comfort"},
    {"verse": "He heals the brokenhearted and binds up their wounds.", "reference": "Psalm 147:3", "theme": "Comfort"},
    {"verse": "Blessed are those who mourn, for they will be comforted.", "reference": "Matthew 5:4", "theme": "Comfort"},
    {"verse": "The Lord is near to all who call on him, to all who call on him in truth.", "reference": "Psalm 145:18", "theme": "Comfort"},
    {"verse": "Cast all your anxiety on him because he cares for you.", "reference": "1 Peter 5:7", "theme": "Comfort"},
    {"verse": "Come to me, all you who are weary and burdened, and I will give you rest.", "reference": "Matthew 11:28", "theme": "Comfort"},
    {"verse": "Peace I leave with you; my peace I give you. I do not give to you as the world gives.", "reference": "John 14:27", "theme": "Peace"},
    {"verse": "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.", "reference": "Numbers 6:24-25", "theme": "Blessing"},

    # --- MAY: Wisdom & Guidance (121-151) ---
    {"verse": "Your word is a lamp for my feet, a light on my path.", "reference": "Psalm 119:105", "theme": "Wisdom"},
    {"verse": "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", "reference": "James 1:5", "theme": "Wisdom"},
    {"verse": "The fear of the Lord is the beginning of wisdom.", "reference": "Proverbs 9:10", "theme": "Wisdom"},
    {"verse": "For the Lord gives wisdom; from his mouth come knowledge and understanding.", "reference": "Proverbs 2:6", "theme": "Wisdom"},
    {"verse": "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", "reference": "Psalm 32:8", "theme": "Guidance"},
    {"verse": "The Lord will guide you always; he will satisfy your needs in a sun-scorched land.", "reference": "Isaiah 58:11", "theme": "Guidance"},
    {"verse": "Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, 'This is the way; walk in it.'", "reference": "Isaiah 30:21", "theme": "Guidance"},
    {"verse": "Show me your ways, Lord, teach me your paths.", "reference": "Psalm 25:4", "theme": "Guidance"},
    {"verse": "The Lord makes firm the steps of the one who delights in him.", "reference": "Psalm 37:23", "theme": "Guidance"},
    {"verse": "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", "reference": "2 Timothy 3:16", "theme": "Wisdom"},
    {"verse": "How sweet are your words to my taste, sweeter than honey to my mouth!", "reference": "Psalm 119:103", "theme": "Wisdom"},
    {"verse": "For the word of God is alive and active. Sharper than any double-edged sword.", "reference": "Hebrews 4:12", "theme": "Wisdom"},
    {"verse": "Do not merely listen to the word, and so deceive yourselves. Do what it says.", "reference": "James 1:22", "theme": "Wisdom"},
    {"verse": "Blessed is the one who does not walk in step with the wicked, but whose delight is in the law of the Lord.", "reference": "Psalm 1:1-2", "theme": "Wisdom"},
    {"verse": "The unfolding of your words gives light; it gives understanding to the simple.", "reference": "Psalm 119:130", "theme": "Wisdom"},
    {"verse": "I have hidden your word in my heart that I might not sin against you.", "reference": "Psalm 119:11", "theme": "Wisdom"},
    {"verse": "Get wisdom, get understanding; do not forget my words or turn away from them.", "reference": "Proverbs 4:5", "theme": "Wisdom"},
    {"verse": "The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding.", "reference": "Proverbs 4:7", "theme": "Wisdom"},
    {"verse": "Blessed are those who find wisdom, those who gain understanding.", "reference": "Proverbs 3:13", "theme": "Wisdom"},
    {"verse": "Plans fail for lack of counsel, but with many advisers they succeed.", "reference": "Proverbs 15:22", "theme": "Wisdom"},
    {"verse": "The heart of the discerning acquires knowledge, for the ears of the wise seek it out.", "reference": "Proverbs 18:15", "theme": "Wisdom"},
    {"verse": "How much better to get wisdom than gold, to get insight rather than silver!", "reference": "Proverbs 16:16", "theme": "Wisdom"},
    {"verse": "But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy.", "reference": "James 3:17", "theme": "Wisdom"},
    {"verse": "The wise in heart accept commands, but a chattering fool comes to ruin.", "reference": "Proverbs 10:8", "theme": "Wisdom"},
    {"verse": "A wise son brings joy to his father, but a foolish son brings grief to his mother.", "reference": "Proverbs 10:1", "theme": "Wisdom"},
    {"verse": "The way of fools seems right to them, but the wise listen to advice.", "reference": "Proverbs 12:15", "theme": "Wisdom"},
    {"verse": "Walk with the wise and become wise, for a companion of fools suffers harm.", "reference": "Proverbs 13:20", "theme": "Wisdom"},
    {"verse": "The teaching of the wise is a fountain of life, turning a person from the snares of death.", "reference": "Proverbs 13:14", "theme": "Wisdom"},
    {"verse": "Whoever is patient has great understanding, but one who is quick-tempered displays folly.", "reference": "Proverbs 14:29", "theme": "Wisdom"},
    {"verse": "A gentle answer turns away wrath, but a harsh word stirs up anger.", "reference": "Proverbs 15:1", "theme": "Wisdom"},
    {"verse": "Commit to the Lord whatever you do, and he will establish your plans.", "reference": "Proverbs 16:3", "theme": "Guidance"},

    # --- JUNE: Prayer & Worship (152-181) ---
    {"verse": "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", "reference": "Philippians 4:6", "theme": "Prayer"},
    {"verse": "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", "reference": "Philippians 4:7", "theme": "Peace"},
    {"verse": "Pray continually.", "reference": "1 Thessalonians 5:17", "theme": "Prayer"},
    {"verse": "Call to me and I will answer you and tell you great and unsearchable things you do not know.", "reference": "Jeremiah 33:3", "theme": "Prayer"},
    {"verse": "If my people, who are called by my name, will humble themselves and pray, I will hear from heaven.", "reference": "2 Chronicles 7:14", "theme": "Prayer"},
    {"verse": "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", "reference": "Matthew 7:7", "theme": "Prayer"},
    {"verse": "The Lord hears the righteous.", "reference": "Psalm 34:17", "theme": "Prayer"},
    {"verse": "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.", "reference": "1 John 5:14", "theme": "Prayer"},
    {"verse": "The prayer of a righteous person is powerful and effective.", "reference": "James 5:16", "theme": "Prayer"},
    {"verse": "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us.", "reference": "Romans 8:26", "theme": "Prayer"},
    {"verse": "Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.", "reference": "Hebrews 4:16", "theme": "Prayer"},
    {"verse": "Devote yourselves to prayer, being watchful and thankful.", "reference": "Colossians 4:2", "theme": "Prayer"},
    {"verse": "I love the Lord, for he heard my voice; he heard my cry for mercy.", "reference": "Psalm 116:1", "theme": "Prayer"},
    {"verse": "Come, let us sing for joy to the Lord; let us shout aloud to the Rock of our salvation.", "reference": "Psalm 95:1", "theme": "Worship"},
    {"verse": "Shout for joy to the Lord, all the earth. Worship the Lord with gladness; come before him with joyful songs.", "reference": "Psalm 100:1-2", "theme": "Worship"},
    {"verse": "God is spirit, and his worshipers must worship in the Spirit and in truth.", "reference": "John 4:24", "theme": "Worship"},
    {"verse": "I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds.", "reference": "Psalm 9:1", "theme": "Worship"},
    {"verse": "Let everything that has breath praise the Lord!", "reference": "Psalm 150:6", "theme": "Worship"},
    {"verse": "Great is the Lord and most worthy of praise; his greatness no one can fathom.", "reference": "Psalm 145:3", "theme": "Worship"},
    {"verse": "I will give thanks to you, Lord, with all my heart; I will tell of all your wonderful deeds.", "reference": "Psalm 9:1", "theme": "Worship"},
    {"verse": "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.", "reference": "Psalm 100:4", "theme": "Worship"},
    {"verse": "Praise the Lord, my soul; all my inmost being, praise his holy name.", "reference": "Psalm 103:1", "theme": "Worship"},
    {"verse": "I will bless the Lord at all times; his praise will always be on my lips.", "reference": "Psalm 34:1", "theme": "Worship"},
    {"verse": "O Lord, you are my God; I will exalt you and praise your name.", "reference": "Isaiah 25:1", "theme": "Worship"},
    {"verse": "The Lord is my shepherd, I lack nothing.", "reference": "Psalm 23:1", "theme": "Trust"},
    {"verse": "He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul.", "reference": "Psalm 23:2-3", "theme": "Peace"},
    {"verse": "Surely goodness and love will follow me all the days of my life.", "reference": "Psalm 23:6", "theme": "Blessing"},
    {"verse": "This is the day the Lord has made; let us rejoice and be glad in it.", "reference": "Psalm 118:24", "theme": "Joy"},
    {"verse": "Sing to the Lord a new song, for he has done marvelous things.", "reference": "Psalm 98:1", "theme": "Worship"},
    {"verse": "I will sing to the Lord all my life; I will sing praise to my God as long as I live.", "reference": "Psalm 104:33", "theme": "Worship"},

    # --- JULY: Joy & Peace (182-212) ---
    {"verse": "The joy of the Lord is your strength.", "reference": "Nehemiah 8:10", "theme": "Joy"},
    {"verse": "Rejoice in the Lord always. I will say it again: Rejoice!", "reference": "Philippians 4:4", "theme": "Joy"},
    {"verse": "You make known to me the path of life; you will fill me with joy in your presence.", "reference": "Psalm 16:11", "theme": "Joy"},
    {"verse": "The Lord has done great things for us, and we are filled with joy.", "reference": "Psalm 126:3", "theme": "Joy"},
    {"verse": "A cheerful heart is good medicine, but a crushed spirit dries up the bones.", "reference": "Proverbs 17:22", "theme": "Joy"},
    {"verse": "Weeping may stay for the night, but rejoicing comes in the morning.", "reference": "Psalm 30:5", "theme": "Joy"},
    {"verse": "Satisfy us in the morning with your unfailing love, that we may sing for joy and be glad all our days.", "reference": "Psalm 90:14", "theme": "Joy"},
    {"verse": "I have told you this so that my joy may be in you and your joy may be complete.", "reference": "John 15:11", "theme": "Joy"},
    {"verse": "The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.", "reference": "Galatians 5:22-23", "theme": "Character"},
    {"verse": "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace.", "reference": "Colossians 3:15", "theme": "Peace"},
    {"verse": "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", "reference": "Isaiah 26:3", "theme": "Peace"},
    {"verse": "The Lord gives strength to his people; the Lord blesses his people with peace.", "reference": "Psalm 29:11", "theme": "Peace"},
    {"verse": "Grace and peace to you from God our Father and from the Lord Jesus Christ.", "reference": "Romans 1:7", "theme": "Peace"},
    {"verse": "Blessed are the peacemakers, for they will be called children of God.", "reference": "Matthew 5:9", "theme": "Peace"},
    {"verse": "Now may the Lord of peace himself give you peace at all times and in every way.", "reference": "2 Thessalonians 3:16", "theme": "Peace"},
    {"verse": "Make every effort to live in peace with everyone and to be holy.", "reference": "Hebrews 12:14", "theme": "Peace"},
    {"verse": "Do not let your hearts be troubled. You believe in God; believe also in me.", "reference": "John 14:1", "theme": "Peace"},
    {"verse": "I have told you these things, so that in me you may have peace.", "reference": "John 16:33", "theme": "Peace"},
    {"verse": "In this world you will have trouble. But take heart! I have overcome the world.", "reference": "John 16:33", "theme": "Courage"},
    {"verse": "Be still, and know that I am God.", "reference": "Psalm 46:10", "theme": "Peace"},
    {"verse": "The Lord will fight for you; you need only to be still.", "reference": "Exodus 14:14", "theme": "Peace"},
    {"verse": "Great peace have those who love your law, and nothing can make them stumble.", "reference": "Psalm 119:165", "theme": "Peace"},
    {"verse": "Delight yourself in the Lord, and he will give you the desires of your heart.", "reference": "Psalm 37:4", "theme": "Joy"},
    {"verse": "Taste and see that the Lord is good; blessed is the one who takes refuge in him.", "reference": "Psalm 34:8", "theme": "Joy"},
    {"verse": "The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures.", "reference": "Psalm 23:1-2", "theme": "Peace"},
    {"verse": "He says, 'Be still, and know that I am God; I will be exalted among the nations.'", "reference": "Psalm 46:10", "theme": "Peace"},
    {"verse": "Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken.", "reference": "Isaiah 54:10", "theme": "Peace"},
    {"verse": "I will lie down and sleep in peace, for you alone, Lord, make me dwell in safety.", "reference": "Psalm 4:8", "theme": "Peace"},
    {"verse": "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus.", "reference": "1 Thessalonians 5:16-18", "theme": "Joy"},
    {"verse": "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.", "reference": "James 1:2", "theme": "Joy"},
    {"verse": "For his anger lasts only a moment, but his favor lasts a lifetime.", "reference": "Psalm 30:5", "theme": "Joy"},

    # --- AUGUST: Identity & Purpose (213-243) ---
    {"verse": "I praise you because I am fearfully and wonderfully made; your works are wonderful.", "reference": "Psalm 139:14", "theme": "Identity"},
    {"verse": "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", "reference": "Ephesians 2:10", "theme": "Purpose"},
    {"verse": "Before I formed you in the womb I knew you, before you were born I set you apart.", "reference": "Jeremiah 1:5", "theme": "Identity"},
    {"verse": "But you are a chosen people, a royal priesthood, a holy nation, God's special possession.", "reference": "1 Peter 2:9", "theme": "Identity"},
    {"verse": "So God created mankind in his own image, in the image of God he created them.", "reference": "Genesis 1:27", "theme": "Identity"},
    {"verse": "See, I have engraved you on the palms of my hands.", "reference": "Isaiah 49:16", "theme": "Identity"},
    {"verse": "You did not choose me, but I chose you and appointed you so that you might go and bear fruit.", "reference": "John 15:16", "theme": "Purpose"},
    {"verse": "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", "reference": "2 Corinthians 5:17", "theme": "Identity"},
    {"verse": "For you created my inmost being; you knit me together in my mother's womb.", "reference": "Psalm 139:13", "theme": "Identity"},
    {"verse": "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", "reference": "Romans 8:28", "theme": "Purpose"},
    {"verse": "For I am convinced that neither death nor life, neither angels nor demons, can separate us from the love of God.", "reference": "Romans 8:38", "theme": "Identity"},
    {"verse": "The Lord will fulfill his purpose for me; your steadfast love, O Lord, endures forever.", "reference": "Psalm 138:8", "theme": "Purpose"},
    {"verse": "Many are the plans in a person's heart, but it is the Lord's purpose that prevails.", "reference": "Proverbs 19:21", "theme": "Purpose"},
    {"verse": "For those God foreknew he also predestined to be conformed to the image of his Son.", "reference": "Romans 8:29", "theme": "Purpose"},
    {"verse": "You are the light of the world. A town built on a hill cannot be hidden.", "reference": "Matthew 5:14", "theme": "Purpose"},
    {"verse": "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", "reference": "Matthew 5:16", "theme": "Purpose"},
    {"verse": "You are the salt of the earth.", "reference": "Matthew 5:13", "theme": "Purpose"},
    {"verse": "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", "reference": "Colossians 3:23", "theme": "Character"},
    {"verse": "Do everything in love.", "reference": "1 Corinthians 16:14", "theme": "Character"},
    {"verse": "Whatever is true, whatever is noble, whatever is right, whatever is pure — think about such things.", "reference": "Philippians 4:8", "theme": "Character"},
    {"verse": "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", "reference": "Ephesians 4:32", "theme": "Kindness"},
    {"verse": "Children, obey your parents in the Lord, for this is right.", "reference": "Ephesians 6:1", "theme": "Obedience"},
    {"verse": "A friend loves at all times, and a brother is born for a time of adversity.", "reference": "Proverbs 17:17", "theme": "Friendship"},
    {"verse": "Two are better than one, because they have a good return for their labor.", "reference": "Ecclesiastes 4:9", "theme": "Friendship"},
    {"verse": "As iron sharpens iron, so one person sharpens another.", "reference": "Proverbs 27:17", "theme": "Friendship"},
    {"verse": "Do not be misled: 'Bad company corrupts good character.'", "reference": "1 Corinthians 15:33", "theme": "Wisdom"},
    {"verse": "Bear with each other and forgive one another if any of you has a grievance against someone.", "reference": "Colossians 3:13", "theme": "Forgiveness"},
    {"verse": "Be completely humble and gentle; be patient, bearing with one another in love.", "reference": "Ephesians 4:2", "theme": "Character"},
    {"verse": "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.", "reference": "Philippians 2:3", "theme": "Character"},
    {"verse": "The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.", "reference": "1 Samuel 16:7", "theme": "Identity"},
    {"verse": "I have been crucified with Christ and I no longer live, but Christ lives in me.", "reference": "Galatians 2:20", "theme": "Identity"},

    # --- SEPTEMBER: Creation & Nature (244-273) ---
    {"verse": "In the beginning God created the heavens and the earth.", "reference": "Genesis 1:1", "theme": "Creation"},
    {"verse": "The heavens declare the glory of God; the skies proclaim the work of his hands.", "reference": "Psalm 19:1", "theme": "Creation"},
    {"verse": "For since the creation of the world God's invisible qualities have been clearly seen, being understood from what has been made.", "reference": "Romans 1:20", "theme": "Creation"},
    {"verse": "By the word of the Lord the heavens were made, their starry host by the breath of his mouth.", "reference": "Psalm 33:6", "theme": "Creation"},
    {"verse": "God saw all that he had made, and it was very good.", "reference": "Genesis 1:31", "theme": "Creation"},
    {"verse": "The earth is the Lord's, and everything in it, the world, and all who live in it.", "reference": "Psalm 24:1", "theme": "Creation"},
    {"verse": "He determines the number of the stars and calls them each by name.", "reference": "Psalm 147:4", "theme": "Creation"},
    {"verse": "How many are your works, Lord! In wisdom you made them all; the earth is full of your creatures.", "reference": "Psalm 104:24", "theme": "Creation"},
    {"verse": "When I consider your heavens, the work of your fingers, the moon and the stars, which you have set in place, what is mankind that you are mindful of them?", "reference": "Psalm 8:3-4", "theme": "Creation"},
    {"verse": "The Lord God formed a man from the dust of the ground and breathed into his nostrils the breath of life.", "reference": "Genesis 2:7", "theme": "Creation"},
    {"verse": "Are not two sparrows sold for a penny? Yet not one of them will fall to the ground outside your Father's care.", "reference": "Matthew 10:29", "theme": "Creation"},
    {"verse": "Look at the birds of the air; they do not sow or reap, yet your heavenly Father feeds them. Are you not much more valuable?", "reference": "Matthew 6:26", "theme": "Creation"},
    {"verse": "Consider how the wild flowers grow. They do not labor or spin. Yet I tell you, not even Solomon in all his splendor was dressed like one of these.", "reference": "Luke 12:27", "theme": "Creation"},
    {"verse": "He has made everything beautiful in its time. He has also set eternity in the human heart.", "reference": "Ecclesiastes 3:11", "theme": "Creation"},
    {"verse": "For everything God created is good, and nothing is to be rejected if it is received with thanksgiving.", "reference": "1 Timothy 4:4", "theme": "Creation"},
    {"verse": "Through him all things were made; without him nothing was made that has been made.", "reference": "John 1:3", "theme": "Creation"},
    {"verse": "For by him all things were created: things in heaven and on earth, visible and invisible.", "reference": "Colossians 1:16", "theme": "Creation"},
    {"verse": "He is before all things, and in him all things hold together.", "reference": "Colossians 1:17", "theme": "Creation"},
    {"verse": "The Lord reigns, let the earth be glad; let the distant shores rejoice.", "reference": "Psalm 97:1", "theme": "Creation"},
    {"verse": "Let the heavens rejoice, let the earth be glad; let the sea resound, and all that is in it.", "reference": "Psalm 96:11", "theme": "Creation"},
    {"verse": "For every house is built by someone, but God is the builder of everything.", "reference": "Hebrews 3:4", "theme": "Creation"},
    {"verse": "He spreads out the northern skies over empty space; he suspends the earth over nothing.", "reference": "Job 26:7", "theme": "Creation"},
    {"verse": "Where were you when I laid the earth's foundation? Tell me, if you understand.", "reference": "Job 38:4", "theme": "Creation"},
    {"verse": "You alone are the Lord. You made the heavens, even the highest heavens, and all their starry host.", "reference": "Nehemiah 9:6", "theme": "Creation"},
    {"verse": "The heavens are yours, and yours also the earth; you founded the world and all that is in it.", "reference": "Psalm 89:11", "theme": "Creation"},
    {"verse": "Lift up your eyes and look to the heavens: Who created all these? He who brings out the starry host one by one and calls forth each of them by name.", "reference": "Isaiah 40:26", "theme": "Creation"},
    {"verse": "For as the soil makes the sprout come up, so the Sovereign Lord will make righteousness spring up before all nations.", "reference": "Isaiah 61:11", "theme": "Creation"},
    {"verse": "While the earth remains, seedtime and harvest, cold and heat, summer and winter, day and night shall not cease.", "reference": "Genesis 8:22", "theme": "Creation"},
    {"verse": "He makes grass grow for the cattle, and plants for people to cultivate — bringing forth food from the earth.", "reference": "Psalm 104:14", "theme": "Creation"},
    {"verse": "Then God said, 'Let the land produce vegetation: seed-bearing plants and trees.' And it was so.", "reference": "Genesis 1:11", "theme": "Creation"},

    # --- OCTOBER: Jesus & Salvation (274-304) ---
    {"verse": "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'", "reference": "John 14:6", "theme": "Jesus"},
    {"verse": "For the Son of Man came to seek and to save the lost.", "reference": "Luke 19:10", "theme": "Salvation"},
    {"verse": "If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved.", "reference": "Romans 10:9", "theme": "Salvation"},
    {"verse": "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", "reference": "Romans 6:23", "theme": "Salvation"},
    {"verse": "Jesus Christ is the same yesterday and today and forever.", "reference": "Hebrews 13:8", "theme": "Jesus"},
    {"verse": "For there is one God and one mediator between God and mankind, the man Christ Jesus.", "reference": "1 Timothy 2:5", "theme": "Jesus"},
    {"verse": "In him was life, and that life was the light of all mankind.", "reference": "John 1:4", "theme": "Jesus"},
    {"verse": "The Word became flesh and made his dwelling among us. We have seen his glory.", "reference": "John 1:14", "theme": "Jesus"},
    {"verse": "For God did not send his Son into the world to condemn the world, but to save the world through him.", "reference": "John 3:17", "theme": "Salvation"},
    {"verse": "I am the good shepherd. The good shepherd lays down his life for the sheep.", "reference": "John 10:11", "theme": "Jesus"},
    {"verse": "I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.", "reference": "John 6:35", "theme": "Jesus"},
    {"verse": "I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.", "reference": "John 8:12", "theme": "Jesus"},
    {"verse": "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.", "reference": "John 15:5", "theme": "Jesus"},
    {"verse": "I am the resurrection and the life. The one who believes in me will live, even though they die.", "reference": "John 11:25", "theme": "Jesus"},
    {"verse": "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.", "reference": "Acts 4:12", "theme": "Salvation"},
    {"verse": "If we confess our sins, he is faithful and just and will forgive us our sins.", "reference": "1 John 1:9", "theme": "Forgiveness"},
    {"verse": "For all have sinned and fall short of the glory of God.", "reference": "Romans 3:23", "theme": "Salvation"},
    {"verse": "He himself bore our sins in his body on the cross, so that we might die to sins and live for righteousness.", "reference": "1 Peter 2:24", "theme": "Salvation"},
    {"verse": "God made him who had no sin to be sin for us, so that in him we might become the righteousness of God.", "reference": "2 Corinthians 5:21", "theme": "Salvation"},
    {"verse": "There is therefore now no condemnation for those who are in Christ Jesus.", "reference": "Romans 8:1", "theme": "Salvation"},
    {"verse": "He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son.", "reference": "Colossians 1:13", "theme": "Salvation"},
    {"verse": "In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace.", "reference": "Ephesians 1:7", "theme": "Salvation"},
    {"verse": "But when the kindness and love of God our Savior appeared, he saved us, not because of righteous things we had done, but because of his mercy.", "reference": "Titus 3:4-5", "theme": "Salvation"},
    {"verse": "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.", "reference": "Romans 5:1", "theme": "Salvation"},
    {"verse": "Whoever believes in the Son has eternal life.", "reference": "John 3:36", "theme": "Salvation"},
    {"verse": "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.", "reference": "John 1:12", "theme": "Salvation"},
    {"verse": "Everyone who calls on the name of the Lord will be saved.", "reference": "Romans 10:13", "theme": "Salvation"},
    {"verse": "And surely I am with you always, to the very end of the age.", "reference": "Matthew 28:20", "theme": "Jesus"},
    {"verse": "For where two or three gather in my name, there am I with them.", "reference": "Matthew 18:20", "theme": "Jesus"},
    {"verse": "Jesus said, 'Let the little children come to me, and do not hinder them, for the kingdom of heaven belongs to such as these.'", "reference": "Matthew 19:14", "theme": "Jesus"},
    {"verse": "He took the children in his arms, placed his hands on them and blessed them.", "reference": "Mark 10:16", "theme": "Jesus"},

    # --- NOVEMBER: Gratitude & Service (305-334) ---
    {"verse": "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.", "reference": "1 Thessalonians 5:18", "theme": "Gratitude"},
    {"verse": "Every good and perfect gift is from above, coming down from the Father of the heavenly lights.", "reference": "James 1:17", "theme": "Gratitude"},
    {"verse": "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.", "reference": "Psalm 100:4", "theme": "Gratitude"},
    {"verse": "Oh give thanks to the Lord, for he is good, for his steadfast love endures forever.", "reference": "Psalm 136:1", "theme": "Gratitude"},
    {"verse": "I will give thanks to the Lord because of his righteousness; I will sing the praises of the name of the Lord Most High.", "reference": "Psalm 7:17", "theme": "Gratitude"},
    {"verse": "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom.", "reference": "Colossians 3:16", "theme": "Gratitude"},
    {"verse": "Thanks be to God for his indescribable gift!", "reference": "2 Corinthians 9:15", "theme": "Gratitude"},
    {"verse": "I will praise God's name in song and glorify him with thanksgiving.", "reference": "Psalm 69:30", "theme": "Gratitude"},
    {"verse": "Let us come before him with thanksgiving and extol him with music and song.", "reference": "Psalm 95:2", "theme": "Gratitude"},
    {"verse": "Giving thanks always and for everything to God the Father in the name of our Lord Jesus Christ.", "reference": "Ephesians 5:20", "theme": "Gratitude"},
    {"verse": "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.", "reference": "Mark 10:45", "theme": "Service"},
    {"verse": "Each of you should use whatever gift you have received to serve others, as faithful stewards of God's grace.", "reference": "1 Peter 4:10", "theme": "Service"},
    {"verse": "Serve one another humbly in love.", "reference": "Galatians 5:13", "theme": "Service"},
    {"verse": "Whatever you did for one of the least of these brothers and sisters of mine, you did for me.", "reference": "Matthew 25:40", "theme": "Service"},
    {"verse": "In everything I did, I showed you that by this kind of hard work we must help the weak.", "reference": "Acts 20:35", "theme": "Service"},
    {"verse": "It is more blessed to give than to receive.", "reference": "Acts 20:35", "theme": "Service"},
    {"verse": "And do not forget to do good and to share with others, for with such sacrifices God is pleased.", "reference": "Hebrews 13:16", "theme": "Service"},
    {"verse": "Religion that God our Father accepts as pure and faultless is this: to look after orphans and widows in their distress.", "reference": "James 1:27", "theme": "Service"},
    {"verse": "Carry each other's burdens, and in this way you will fulfill the law of Christ.", "reference": "Galatians 6:2", "theme": "Service"},
    {"verse": "Therefore encourage one another and build each other up, just as in fact you are doing.", "reference": "1 Thessalonians 5:11", "theme": "Kindness"},
    {"verse": "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", "reference": "Galatians 6:9", "theme": "Service"},
    {"verse": "Each one should test their own actions. Then they can take pride in themselves alone.", "reference": "Galatians 6:4", "theme": "Character"},
    {"verse": "Be devoted to one another in love. Honor one another above yourselves.", "reference": "Romans 12:10", "theme": "Kindness"},
    {"verse": "Never be lacking in zeal, but keep your spiritual fervor, serving the Lord.", "reference": "Romans 12:11", "theme": "Service"},
    {"verse": "Share with the Lord's people who are in need. Practice hospitality.", "reference": "Romans 12:13", "theme": "Service"},
    {"verse": "Bless those who persecute you; bless and do not curse.", "reference": "Romans 12:14", "theme": "Character"},
    {"verse": "Rejoice with those who rejoice; mourn with those who mourn.", "reference": "Romans 12:15", "theme": "Kindness"},
    {"verse": "Do not repay anyone evil for evil. Be careful to do what is right in the eyes of everyone.", "reference": "Romans 12:17", "theme": "Character"},
    {"verse": "If it is possible, as far as it depends on you, live at peace with everyone.", "reference": "Romans 12:18", "theme": "Peace"},
    {"verse": "Do not be overcome by evil, but overcome evil with good.", "reference": "Romans 12:21", "theme": "Character"},

    # --- DECEMBER: Promises & Eternal Life (335-365) ---
    {"verse": "For unto us a child is born, unto us a son is given, and the government shall be upon his shoulders.", "reference": "Isaiah 9:6", "theme": "Jesus"},
    {"verse": "And he shall be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.", "reference": "Isaiah 9:6", "theme": "Jesus"},
    {"verse": "For nothing will be impossible with God.", "reference": "Luke 1:37", "theme": "Faith"},
    {"verse": "Glory to God in the highest heaven, and on earth peace to those on whom his favor rests.", "reference": "Luke 2:14", "theme": "Peace"},
    {"verse": "She will give birth to a son, and you are to give him the name Jesus, because he will save his people from their sins.", "reference": "Matthew 1:21", "theme": "Jesus"},
    {"verse": "Today in the town of David a Savior has been born to you; he is the Messiah, the Lord.", "reference": "Luke 2:11", "theme": "Jesus"},
    {"verse": "The virgin will conceive and give birth to a son, and they will call him Immanuel — which means 'God with us.'", "reference": "Matthew 1:23", "theme": "Jesus"},
    {"verse": "In my Father's house are many rooms. I am going there to prepare a place for you.", "reference": "John 14:2", "theme": "Heaven"},
    {"verse": "And if I go and prepare a place for you, I will come back and take you to be with me.", "reference": "John 14:3", "theme": "Heaven"},
    {"verse": "For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.", "reference": "2 Corinthians 4:17", "theme": "Heaven"},
    {"verse": "No eye has seen, no ear has heard, no mind has conceived what God has prepared for those who love him.", "reference": "1 Corinthians 2:9", "theme": "Heaven"},
    {"verse": "He who was seated on the throne said, 'I am making everything new!'", "reference": "Revelation 21:5", "theme": "Heaven"},
    {"verse": "There will be no more night. They will not need the light of a lamp or the light of the sun, for the Lord God will give them light.", "reference": "Revelation 22:5", "theme": "Heaven"},
    {"verse": "God will wipe away every tear from their eyes; there shall be no more death, nor sorrow, nor crying.", "reference": "Revelation 21:4", "theme": "Heaven"},
    {"verse": "Then I saw a new heaven and a new earth, for the first heaven and the first earth had passed away.", "reference": "Revelation 21:1", "theme": "Heaven"},
    {"verse": "But our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ.", "reference": "Philippians 3:20", "theme": "Heaven"},
    {"verse": "And God shall wipe away all tears from their eyes.", "reference": "Revelation 7:17", "theme": "Heaven"},
    {"verse": "For to me, to live is Christ and to die is gain.", "reference": "Philippians 1:21", "theme": "Faith"},
    {"verse": "I have fought the good fight, I have finished the race, I have kept the faith.", "reference": "2 Timothy 4:7", "theme": "Faith"},
    {"verse": "Now there is in store for me the crown of righteousness, which the Lord, the righteous Judge, will award to me.", "reference": "2 Timothy 4:8", "theme": "Heaven"},
    {"verse": "Precious in the sight of the Lord is the death of his faithful servants.", "reference": "Psalm 116:15", "theme": "Faith"},
    {"verse": "The Lord is not slow in keeping his promise, as some understand slowness.", "reference": "2 Peter 3:9", "theme": "Faithfulness"},
    {"verse": "Let us hold unswervingly to the hope we profess, for he who promised is faithful.", "reference": "Hebrews 10:23", "theme": "Faithfulness"},
    {"verse": "Faithful is He who calls you, and He also will do it.", "reference": "1 Thessalonians 5:24", "theme": "Faithfulness"},
    {"verse": "If we are faithless, he remains faithful, for he cannot disown himself.", "reference": "2 Timothy 2:13", "theme": "Faithfulness"},
    {"verse": "His master replied, 'Well done, good and faithful servant! Come and share your master's happiness!'", "reference": "Matthew 25:23", "theme": "Faithfulness"},
    {"verse": "Be faithful, even to the point of death, and I will give you life as your victor's crown.", "reference": "Revelation 2:10", "theme": "Faithfulness"},
    {"verse": "The Lord is faithful, and he will strengthen you and protect you from the evil one.", "reference": "2 Thessalonians 3:3", "theme": "Faithfulness"},
    {"verse": "God is faithful, who has called you into fellowship with his Son, Jesus Christ our Lord.", "reference": "1 Corinthians 1:9", "theme": "Faithfulness"},
    {"verse": "The grass withers and the flowers fall, but the word of our God endures forever.", "reference": "Isaiah 40:8", "theme": "Faithfulness"},
    {"verse": "Jesus Christ is the same yesterday and today and forever.", "reference": "Hebrews 13:8", "theme": "Faithfulness"},
]

assert len(DAILY_VERSES) >= 365, f"Need 365 verses, have {len(DAILY_VERSES)}"
